"""DeadLetterRecord (design.md Data Models, Requirement 8.3).

Requirement 8.3: "WHEN retries are exhausted for a transient error THEN
the system SHALL persist a DeadLetterRecord (task envelope reference,
error detail, retry count, trace ID) and SHALL NOT silently drop the
failure."
"""

from __future__ import annotations

from datetime import datetime

from pydantic import ConfigDict, Field

from daf.models.common import ArtifactRef, DafBaseModel
from daf.models.types import RunId, TraceId


class DeadLetterRecord(DafBaseModel):
    """A persisted record of a task whose retries were exhausted.

    `dead_letter_id` is generated by the repository layer (Task 5.5) at
    write time, not supplied by the caller — see
    `DeadLetterRecordRepository.create`.
    """

    dead_letter_id: str = Field(min_length=1, alias="deadLetterId")
    run_id: RunId = Field(alias="runId")
    task_envelope_ref: ArtifactRef = Field(alias="taskEnvelopeRef")
    error_detail: str = Field(min_length=1, alias="errorDetail")
    retry_count: int = Field(ge=0, alias="retryCount")
    trace_id: TraceId = Field(alias="traceId")
    created_at: datetime = Field(alias="createdAt")

    model_config = ConfigDict(extra="forbid", validate_assignment=True, populate_by_name=True)
